### ISSUE TITLE
Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]

### ISSUE THREAD

**Issue by suanmb** [fcrespel/jenkins-cas-plugin#7]
In accordance with the use of plug-in configuration, the results reported the following error, what should I do

/root/.jenkins/config.xml
`<securityRealm class="org.jenkinsci.plugins.cas.CasSecurityRealm" plugin="cas-plugin@1.3.0">
    <casServerUrl>https://cas.***.net/cas/</casServerUrl>
    <casProtocol class="org.jenkinsci.plugins.cas.protocols.Cas20Protocol">
      <authoritiesAttribute>groups,roles</authoritiesAttribute>
      <fullNameAttribute>cn</fullNameAttribute>
      <emailAttribute>mail</emailAttribute>
      <proxyEnabled>false</proxyEnabled>
      <proxyAllowAny>false</proxyAllowAny>
      <proxyAllowList></proxyAllowList>
    </casProtocol>
    <forceRenewal>false</forceRenewal>
    <enableSingleSignOut>false</enableSingleSignOut>
    <enableRestApi>false</enableRestApi>
  </securityRealm>`

hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'casFilter': Cannot create inner bean '(inner bean)' of type [org.jenkinsci.plugins.cas.spring.security.CasSingleSignOutFilter] while setting bean property 'filters' with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Cannot create inner bean '(inner bean)' of type [org.jasig.cas.client.session.SingleSignOutHandler] while setting bean property 'singleSignOutHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at hudson.WebAppMain$3.run(WebAppMain.java:248)
Caused by: org.jvnet.hudson.reactor.ReactorException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'casFilter': Cannot create inner bean '(inner bean)' of type [org.jenkinsci.plugins.cas.spring.security.CasSingleSignOutFilter] while setting bean property 'filters' with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Cannot create inner bean '(inner bean)' of type [org.jasig.cas.client.session.SingleSignOutHandler] while setting bean property 'singleSignOutHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:47)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1109)
	at jenkins.model.Jenkins.<init>(Jenkins.java:925)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:231)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'casFilter': Cannot create inner bean '(inner bean)' of type [org.jenkinsci.plugins.cas.spring.security.CasSingleSignOutFilter] while setting bean property 'filters' with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Cannot create inner bean '(inner bean)' of type [org.jasig.cas.client.session.SingleSignOutHandler] while setting bean property 'singleSignOutHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:230)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:287)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1010)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:472)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:429)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
	at hudson.util.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:94)
	at hudson.util.spring.BeanBuilder.createApplicationContext(BeanBuilder.java:391)
	at org.jenkinsci.plugins.cas.CasSecurityRealm.getApplicationContext(CasSecurityRealm.java:151)
	at org.jenkinsci.plugins.cas.CasSecurityRealm.createFilter(CasSecurityRealm.java:230)
	at hudson.security.HudsonFilter.reset(HudsonFilter.java:144)
	at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2514)
	at jenkins.model.Jenkins$19.run(Jenkins.java:3109)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Cannot create inner bean '(inner bean)' of type [org.jasig.cas.client.session.SingleSignOutHandler] while setting bean property 'singleSignOutHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:230)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1010)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:472)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:219)
	... 32 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1010)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:472)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:219)
	... 40 more
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'casServerUrlPrefix' of bean class [org.jasig.cas.client.session.SingleSignOutHandler]: Bean property 'casServerUrlPrefix' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:801)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:651)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:78)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:59)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1276)
	... 46 more

**Comment by fcrespel** [comment]
Which version of Jenkins are you using?
Could you please also list the contents of your /root/.jenkins/plugins/cas-plugin/WEB-INF/lib/ directory?

**Comment by suanmb** [comment]
No problem,  I made a mistake of the tomcat directory, configuration errors！thanks u

**Comment by suanmb** [comment]
No problem,  I made a mistake of the tomcat directory, configuration errors！thanks u
